on:
  push:
    tags: ["v1.0.1"]

permissions:
  contents: write
  packages: write

jobs:
  release:
    if: startsWith(github.ref, 'refs/tags/v1.0.1')
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: npm i -g --force corepack && corepack enable

      - name: Install Node.js, NPM and PNPM
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install

      - name: Release Electron app for macOS (${{ matrix.arch }})
        uses: daltonmenezes/action-electron-builder@v1.0.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          package_manager: "pnpm"
          args: "--${{ matrix.arch }}"
